# -*- coding: utf-8 -*-
"""knn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gUxIRO6pl9qJOre0vnKAvpLJJgu17rwM
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def dimage(sample):
  img = sample.reshape((28,28))
  plt.imshow(img)
  plt.show()

def distance(x1,x2):
  return np.sqrt(sum(x1-x2)**2)

def knn(x,y,query,k=1000):
  values = []
  m = x.shape[0]
  for i in range(m):
    d = distance(query,x[i])
    values.append((d,y[i]))
  values = sorted(values)
  values = values[:k]
  values = np.array(values)
  new_values = np.unique(values[:,1],return_counts=True)
  index = new_values[1].argmax()
  pred = new_values[0][index]
  return pred

df = pd.read_csv('mnist_train.csv')
df1 = pd.read_csv('mnist_test.csv')
#print(df.shape)
#print(df.columns)
data = df.values
data1 = df1.values
#print(data.shape)
#print(type(data))
x_train = data[:,1:]
y_train = data[:,:1]
x_test = data1[:,1:]
y_test = data1[:,:1]
#split = int(0.8*x.shape[0])
#x_train = x[:split,:]
#y_train = y[:split,:]
#x_test = x[split:,:]
#y_test = y[split:,:]

pred = knn(x_train, y_train, x_test[80])
print(int(pred))
dimage(x_test[80])
print(y_test[80])